-- Backend for the standalone Day 1 Knowledge Check page (day1-knowledge-check.html
-- at the site root). This is not part of the ERP proper — trainees filling it out
-- have no ERP account — so it gets its own table with its own, separate RLS
-- policies scoped to the `anon` role, rather than joining the `authenticated`-only
-- policies the rest of this schema uses (see 006_require_authenticated.sql).
--
-- The page's "supervisor view" PIN gate is UI-only (the PIN lives in the page's
-- JavaScript), matching the same soft, UI-only access model already used
-- elsewhere in this project. Anyone with the anon key (embedded in the page,
-- same as the rest of the ERP client) can insert or read rows in this table —
-- do not put anything more sensitive than trainee quiz answers in it.

create table if not exists submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  submitted_at timestamptz not null default now(),
  timed_out boolean not null default false,
  video_recorded boolean not null default false,
  video_duration_seconds integer not null default 0,
  video_url text,
  answers jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table submissions enable row level security;

create policy submissions_anon_insert on submissions for insert to anon with check (true);
create policy submissions_anon_select on submissions for select to anon using (true);

-- Storage bucket for the recorded Q3 video answers. Public so the supervisor
-- view can play them back directly via getPublicUrl() without a signed URL.
insert into storage.buckets (id, name, public)
values ('trainee-videos', 'trainee-videos', true)
on conflict (id) do nothing;

create policy trainee_videos_anon_insert on storage.objects
  for insert to anon with check (bucket_id = 'trainee-videos');

create policy trainee_videos_anon_select on storage.objects
  for select to anon using (bucket_id = 'trainee-videos');
